on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # should be 3
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      run: echo ${{github.run_number}}
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: ohana-artifact-${{ github.run_number }}
        path: .
        run: ls  
